# Análisis de Datos de un Sensor de Temperatura

### Tenemos datos de temperatura registrados cada hora en diferentes sensores durante una semana. Usaremos NumPy para:

### - Generar datos aleatorios de temperatura.
### - Aplanar los arreglos para facilitar análisis.
### - Concatenar datos de diferentes sensores.
### - Cambiar la forma para organizar los datos por días.
### - Aplicar indexación y slicing para extraer información.
### - Manejar tipos de datos.

## 1. Generar datos aleatorios

Generamos datos de temperatura simulados para 3 sensores durante una semana (7 días, 24 horas por día).

In [37]:
# Importar NumPy
import numpy as np

# Fijar semilla para reproducibilidad
np.random.seed(42)

# Generar datos aleatorios de temperatura (en °C) para 3 sensores (7 días x 24 horas)
#Sensor 1
sensor1 = np.random.uniform(16, 34, size=( 7, 24))
sensor1 = np.round(sensor1, 2)
#Sensor 2
sensor2 = np.random.uniform(16, 34, size=( 7, 24))
sensor2 = np.round(sensor2, 2)
#Sensor 3
sensor3 = np.random.uniform(16, 34, size=( 7, 24))
sensor3 = np.round(sensor3, 2)
# Imprimir los sensores generados
print(sensor1)
print("________________________________________________________________________________________________________________________________________")
print(sensor2)
print("________________________________________________________________________________________________________________________________________")
print(sensor3)
print("________________________________________________________________________________________________________________________________________")
# Mostrar una muestra de datos del primer día (matriz del primer sensor)
print("\nDatos del primer sensor para el primer día:")
print(sensor1[0])


[[22.74 33.11 29.18 26.78 18.81 18.81 17.05 31.59 26.82 28.75 16.37 33.46
  30.98 19.82 19.27 19.3  21.48 25.45 23.78 21.24 27.01 18.51 21.26 22.59]
 [24.21 30.13 19.59 25.26 26.66 16.84 26.94 19.07 17.17 33.08 33.38 30.55
  21.48 17.76 28.32 23.92 18.2  24.91 16.62 32.37 20.66 27.93 21.61 25.36]
 [25.84 19.33 33.45 29.95 32.91 32.11 26.76 32.59 17.59 19.53 16.81 21.86
  23.   20.88 30.92 22.42 21.06 25.77 18.54 30.44 17.34 33.76 29.9  19.58]
 [16.1  30.68 28.72 29.12 29.88 17.33 22.45 18.09 31.54 27.22 21.96 17.14
  21.6  21.85 29.13 27.48 31.97 24.5  18.15 28.84 29.69 26.1  29.88 24.89]
 [25.41 23.7  16.46 17.94 16.57 27.46 21.66 25.15 32.34 20.49 23.39 29.6
  20.12 17.39 21.22 18.9  32.73 30.55 27.4  31.69 30.47 19.36 32.07 25.71]
 [30.53 32.13 21.72 17.98 20.1  23.69 30.72 31.49 16.13 25.19 23.51 20.
  18.16 22.08 32.97 21.82 25.34 28.65 22.55 33.49 33.32 20.53 24.95 21.42]
 [21.13 16.66 26.97 25.05 16.93 21.02 32.35 20.31 18.61 24.81 33.74 20.36
  28.1  29.71 20.28 29.11 22.62 27.

## 2. Aplanar los datos

Convertir la matriz de (7,24) en un arreglo de 168 valores (7 días x 24 horas).

In [41]:
sensor1_aplanado=sensor1.ravel()
print(sensor1_aplanado)


[22.74 33.11 29.18 26.78 18.81 18.81 17.05 31.59 26.82 28.75 16.37 33.46
 30.98 19.82 19.27 19.3  21.48 25.45 23.78 21.24 27.01 18.51 21.26 22.59
 24.21 30.13 19.59 25.26 26.66 16.84 26.94 19.07 17.17 33.08 33.38 30.55
 21.48 17.76 28.32 23.92 18.2  24.91 16.62 32.37 20.66 27.93 21.61 25.36
 25.84 19.33 33.45 29.95 32.91 32.11 26.76 32.59 17.59 19.53 16.81 21.86
 23.   20.88 30.92 22.42 21.06 25.77 18.54 30.44 17.34 33.76 29.9  19.58
 16.1  30.68 28.72 29.12 29.88 17.33 22.45 18.09 31.54 27.22 21.96 17.14
 21.6  21.85 29.13 27.48 31.97 24.5  18.15 28.84 29.69 26.1  29.88 24.89
 25.41 23.7  16.46 17.94 16.57 27.46 21.66 25.15 32.34 20.49 23.39 29.6
 20.12 17.39 21.22 18.9  32.73 30.55 27.4  31.69 30.47 19.36 32.07 25.71
 30.53 32.13 21.72 17.98 20.1  23.69 30.72 31.49 16.13 25.19 23.51 20.
 18.16 22.08 32.97 21.82 25.34 28.65 22.55 33.49 33.32 20.53 24.95 21.42
 21.13 16.66 26.97 25.05 16.93 21.02 32.35 20.31 18.61 24.81 33.74 20.36
 28.1  29.71 20.28 29.11 22.62 27.38 27.4  25.64 17.63

## 3. Concatenar los datos de los sensores

Juntamos los datos de los 3 sensores para tener una matriz más grande.


In [91]:
sensores = np.array([sensor1,sensor2,sensor3])
sensores_aplanados = sensores.ravel()
sensores_aplanados

array([22.74, 33.11, 29.18, 26.78, 18.81, 18.81, 17.05, 31.59, 26.82,
       28.75, 16.37, 33.46, 30.98, 19.82, 19.27, 19.3 , 21.48, 25.45,
       23.78, 21.24, 27.01, 18.51, 21.26, 22.59, 24.21, 30.13, 19.59,
       25.26, 26.66, 16.84, 26.94, 19.07, 17.17, 33.08, 33.38, 30.55,
       21.48, 17.76, 28.32, 23.92, 18.2 , 24.91, 16.62, 32.37, 20.66,
       27.93, 21.61, 25.36, 25.84, 19.33, 33.45, 29.95, 32.91, 32.11,
       26.76, 32.59, 17.59, 19.53, 16.81, 21.86, 23.  , 20.88, 30.92,
       22.42, 21.06, 25.77, 18.54, 30.44, 17.34, 33.76, 29.9 , 19.58,
       16.1 , 30.68, 28.72, 29.12, 29.88, 17.33, 22.45, 18.09, 31.54,
       27.22, 21.96, 17.14, 21.6 , 21.85, 29.13, 27.48, 31.97, 24.5 ,
       18.15, 28.84, 29.69, 26.1 , 29.88, 24.89, 25.41, 23.7 , 16.46,
       17.94, 16.57, 27.46, 21.66, 25.15, 32.34, 20.49, 23.39, 29.6 ,
       20.12, 17.39, 21.22, 18.9 , 32.73, 30.55, 27.4 , 31.69, 30.47,
       19.36, 32.07, 25.71, 30.53, 32.13, 21.72, 17.98, 20.1 , 23.69,
       30.72, 31.49,

## 4. Cambiar la forma de los datos

Reorganizamos los datos en una matriz de (7 días, 24 horas, 3 sensores) para facilitar el análisis.

In [95]:
# Mostrar del primer dia, las primeras dos horas de los 3 sensores
dos_horas = sensores[:, 0, :2]
dos_horas

array([[22.74, 33.11],
       [16.73, 26.64],
       [31.4 , 28.67]])

## 5. Indexación y slicing

Extraer información especifica

In [87]:
# Temperatura del sensor 2, día 3, hora 12
print("Sensor 2, día 3, hora 12: ", sensor2[2,10:11])
# Datos del día 5 para todos los sensores
dia = sensores[:, 4, ]
dia


Sensor 2, día 3, hora 12:  [33.51]


array([[25.41, 23.7 , 16.46, 17.94, 16.57, 27.46, 21.66, 25.15, 32.34,
        20.49, 23.39, 29.6 , 20.12, 17.39, 21.22, 18.9 , 32.73, 30.55,
        27.4 , 31.69, 30.47, 19.36, 32.07, 25.71],
       [31.79, 29.33, 28.55, 28.64, 22.47, 21.28, 30.57, 30.58, 31.61,
        32.44, 25.2 , 25.03, 30.37, 27.7 , 28.64, 30.32, 32.02, 22.08,
        22.76, 17.69, 26.41, 16.65, 24.38, 25.77],
       [27.13, 17.82, 17.51, 28.62, 17.31, 30.79, 28.71, 17.46, 17.53,
        33.76, 22.74, 22.67, 30.63, 33.05, 33.75, 29.56, 22.77, 17.5 ,
        29.99, 26.05, 23.64, 32.31, 18.  , 24.87]])

## 6. Convertir tipos de datos

Para ahorrar memoria, convertimos los datos de float64 a float32



In [99]:
tamaño = sensores.astype(np.float32)
print(tamaño.dtype) 

float32
